# Generated by Django 4.1.1 on 2022-10-09 16:17

from django.db import migrations, models
import django.db.models.deletion
import maas.flex_notes


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlexNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "duration_mode",
                    models.CharField(
                        choices=[
                            ("1", "1/1 note"),
                            ("4", "1/4 note"),
                            (".", "staccato 1/4 note"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "tone",
                    models.CharField(
                        choices=[
                            ("N", "nucleus"),
                            ("U", "upper satellite"),
                            ("L", "lower satellite"),
                        ],
                        max_length=1,
                    ),
                ),
                ("degree", models.SmallIntegerField(default=0)),
                ("is_ghosted", models.BooleanField(default=False)),
            ],
            bases=(models.Model, maas.flex_notes.AbstractFlexNote),
        ),
        migrations.CreateModel(
            name="Lexeme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=254, unique=True)),
                ("notes", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PosTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=5, verbose_name="abbreviation")),
                ("name", models.CharField(max_length=126)),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[(0, "open class"), (1, "closed class"), (2, "other")]
                    ),
                ),
            ],
            options={
                "verbose_name": "universal POS tag",
            },
        ),
        migrations.CreateModel(
            name="LexemeFlexNote",
            fields=[
                (
                    "flexnote_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="maas.flexnote",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                (
                    "lexeme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flex_notes",
                        to="maas.lexeme",
                    ),
                ),
            ],
            bases=("maas.flexnote",),
        ),
        migrations.AddConstraint(
            model_name="lexemeflexnote",
            constraint=models.UniqueConstraint(
                models.F("lexeme"),
                models.F("index"),
                name="no_repeat_lexeme_flex_notes",
            ),
        ),
    ]
