# Generated by Django 4.1.2 on 2022-11-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flexnote",
            name="duration_mode",
        ),
        migrations.AddField(
            model_name="flexnote",
            name="size_mode",
            field=models.CharField(
                choices=[
                    ("1", "large (whole) note"),
                    ("4", "medium (1/4) note"),
                    (".", "small (staccato 1/4) note"),
                ],
                default="4",
                max_length=1,
            ),
            preserve_default=False,
        ),
    ]
