# Generated by Django 4.1.2 on 2022-10-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0003_rename_lang_isolang_rename_langname_isolangname_and_more"),
        ("maas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lexemetranslation",
            old_name="lang",
            new_name="iso_lang",
        ),
        migrations.AlterUniqueTogether(
            name="lexemetranslation",
            unique_together={("word", "iso_lang"), ("lexeme", "iso_lang")},
        ),
    ]
