# Generated by Django 4.1.1 on 2022-10-09 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("maas", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lexemeflexnote",
            name="flexnote_ptr",
        ),
        migrations.AddField(
            model_name="lexemeflexnote",
            name="flex_note",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                parent_link=True,
                primary_key=True,
                serialize=False,
                to="maas.flexnote",
            ),
            preserve_default=False,
        ),
    ]
