# Generated by Django 4.1.1 on 2022-10-15 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=126, unique=True)),
                (
                    "name",
                    models.CharField(
                        max_length=126, verbose_name="translated display name"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PosTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=5, verbose_name="abbreviation")),
                ("name", models.CharField(max_length=126)),
                (
                    "category",
                    models.SmallIntegerField(
                        choices=[(0, "open class"), (1, "closed class"), (2, "other")]
                    ),
                ),
            ],
            options={
                "verbose_name": "universal POS tag",
            },
        ),
        migrations.CreateModel(
            name="SpacyModelSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
                (
                    "scale",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="small-to-large scale"
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpacyModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpacyLanguageModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=12)),
                ("package_version", models.CharField(max_length=126)),
                ("downloaded", models.BooleanField(default=False)),
                (
                    "language",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.language",
                    ),
                ),
                (
                    "model_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.spacymodelsize",
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.spacymodeltype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("language", "model_type", "genre", "model_size", "package_version")
                },
            },
        ),
    ]
