# Generated by Django 4.1.2 on 2022-10-24 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GrandfatheredLang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iana_deprecated", models.DateField(null=True)),
                ("iana_added", models.DateField(null=True)),
                ("tag_text", models.TextField(max_length=12)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="IanaSubtagRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_date", models.DateField()),
                ("saved", models.DateTimeField()),
            ],
            options={
                "verbose_name": "IANA Language Subtag Registry",
            },
        ),
        migrations.CreateModel(
            name="Lang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ref_name",
                    models.CharField(max_length=150, verbose_name="reference name"),
                ),
                (
                    "part_3",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        verbose_name="alpha-3 code (ISO 639-3)",
                    ),
                ),
                (
                    "part_1",
                    models.CharField(
                        max_length=2, null=True, verbose_name="alpha-2 code (ISO 639-1)"
                    ),
                ),
                (
                    "part_2b",
                    models.CharField(
                        max_length=3,
                        null=True,
                        verbose_name="bibliographic code (ISO 639-2/B)",
                    ),
                ),
                (
                    "part_2t",
                    models.CharField(
                        max_length=3,
                        null=True,
                        verbose_name="terminological code (ISO 639-2/T)",
                    ),
                ),
                (
                    "lang_type",
                    models.CharField(
                        choices=[
                            ("A", "ancient"),
                            ("C", "constructed"),
                            ("E", "extinct"),
                            ("H", "historical"),
                            ("L", "living"),
                            ("S", "special"),
                        ],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("I", "individual"),
                            ("M", "macrolanguage"),
                            ("S", "special"),
                        ],
                        max_length=1,
                    ),
                ),
                ("comment", models.CharField(max_length=150, null=True)),
                (
                    "is_wordnet_supported",
                    models.BooleanField(
                        default=False,
                        verbose_name="supported by the Open Multilingual Wordnet",
                    ),
                ),
                (
                    "macrolanguage",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individuals",
                        to="language.lang",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISO 639 language",
            },
        ),
        migrations.CreateModel(
            name="PosTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=5, verbose_name="abbreviation")),
                ("name", models.CharField(max_length=126)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("O", "open class"),
                            ("C", "closed class"),
                            ("X", "other"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "universal POS tag",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iana_deprecated", models.DateField(null=True)),
                ("iana_added", models.DateField(null=True)),
                ("un_m49", models.CharField(max_length=3)),
                (
                    "iso_3166",
                    models.CharField(
                        max_length=2, verbose_name="alpha-2 (ISO 3166-1) code"
                    ),
                ),
                (
                    "iana_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.ianasubtagregistry",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iana_deprecated", models.DateField(null=True)),
                ("iana_added", models.DateField(null=True)),
                (
                    "code",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="ISO 15924 code"
                    ),
                ),
                (
                    "no",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="ISO 15924 number"
                    ),
                ),
                (
                    "name_en",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="English name"
                    ),
                ),
                (
                    "name_fr",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="nom français"
                    ),
                ),
                (
                    "pva",
                    models.CharField(
                        max_length=150, null=True, verbose_name="property value alias"
                    ),
                ),
                ("unicode_version", models.CharField(max_length=12, null=True)),
                ("script_date", models.DateField()),
                (
                    "iana_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.ianasubtagregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "ISO 15924 script",
            },
        ),
        migrations.CreateModel(
            name="SpacyModelSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
                (
                    "scale",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="small-to-large scale"
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpacyModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iana_deprecated", models.DateField(null=True)),
                ("iana_added", models.DateField(null=True)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("G", "grandfathered"),
                            ("P", "private use"),
                            ("X", "redundant / irregular"),
                            ("L", "Language"),
                            ("E", "Extlang"),
                            ("R", "Region"),
                            ("S", "Script"),
                            ("V", "Variant"),
                        ],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                ("tag", models.CharField(max_length=12, null=True)),
                ("subtag", models.CharField(max_length=12, null=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("C", "collection"),
                            ("M", "macrolanguage"),
                            ("S", "special"),
                            ("P", "private use"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "macrolanguage",
                    models.CharField(
                        max_length=4, null=True, verbose_name="macrolanguage code"
                    ),
                ),
                ("comment", models.CharField(max_length=150, null=True)),
                (
                    "pref_value",
                    models.CharField(
                        max_length=12, null=True, verbose_name="preferred value"
                    ),
                ),
                ("suppress_script", models.CharField(max_length=4, null=True)),
                (
                    "iana_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.ianasubtagregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "BCP 47 language tag",
            },
        ),
        migrations.CreateModel(
            name="Variant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iana_deprecated", models.DateField(null=True)),
                ("iana_added", models.DateField(null=True)),
                ("text", models.CharField(max_length=40)),
                ("digits", models.CharField(max_length=4)),
                (
                    "iana_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.ianasubtagregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFC5646 variant subtag",
            },
        ),
        migrations.CreateModel(
            name="LangTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lang_type",
                    models.CharField(
                        choices=[
                            ("G", "grandfathered"),
                            ("P", "private use"),
                            ("X", "redundant / irregular"),
                            ("L", "Language"),
                            ("E", "Extlang"),
                            ("R", "Region"),
                            ("S", "Script"),
                            ("V", "Variant"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "grandfathered",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.grandfatheredlang",
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.lang",
                        verbose_name="language",
                    ),
                ),
                (
                    "script",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.script",
                    ),
                ),
                ("variants", models.ManyToManyField(to="language.variant")),
            ],
        ),
        migrations.CreateModel(
            name="LangName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "printable",
                    models.CharField(
                        max_length=75, verbose_name="printable translated name"
                    ),
                ),
                (
                    "inverted",
                    models.CharField(
                        max_length=75, verbose_name="inverted translated name"
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="language.lang",
                    ),
                ),
            ],
            options={
                "verbose_name": "language name",
            },
        ),
        migrations.CreateModel(
            name="LangExtension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iana_deprecated", models.DateField(null=True)),
                ("iana_added", models.DateField(null=True)),
                ("text", models.CharField(max_length=11)),
                (
                    "iana_registry",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.ianasubtagregistry",
                    ),
                ),
            ],
            options={
                "verbose_name": "language extension",
            },
        ),
        migrations.AddField(
            model_name="grandfatheredlang",
            name="iana_registry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="language.ianasubtagregistry",
            ),
        ),
        migrations.CreateModel(
            name="GoogleLang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=75)),
                ("supports_source", models.BooleanField()),
                ("supports_target", models.BooleanField()),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="language.lang",
                        verbose_name="language",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.langtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Cloud Translate API language",
            },
        ),
        migrations.CreateModel(
            name="VariantDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=75)),
                (
                    "subtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.variant",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("subtag", "index")},
            },
        ),
        migrations.CreateModel(
            name="SubtagPrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("text", models.CharField(max_length=150)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefixes",
                        to="language.subtag",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFC5646 language tag prefix",
                "unique_together": {("tag", "text"), ("tag", "index")},
            },
        ),
        migrations.CreateModel(
            name="SubtagDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=75)),
                (
                    "subtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.subtag",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("subtag", "index")},
            },
        ),
        migrations.CreateModel(
            name="SpacyLangModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=12)),
                ("package_version", models.CharField(max_length=126)),
                ("downloaded", models.BooleanField(default=False)),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="language.lang"
                    ),
                ),
                (
                    "model_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.spacymodelsize",
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.spacymodeltype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("lang", "model_type", "genre", "model_size", "package_version")
                },
            },
        ),
        migrations.CreateModel(
            name="ScriptDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=75)),
                (
                    "subtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.script",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("subtag", "index")},
            },
        ),
        migrations.CreateModel(
            name="RegionDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=75)),
                (
                    "subtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.region",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("subtag", "index")},
            },
        ),
        migrations.CreateModel(
            name="LangExtDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=75)),
                (
                    "subtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.langextension",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("subtag", "index")},
            },
        ),
        migrations.CreateModel(
            name="GrandfatheredLangDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField(default=0)),
                ("text", models.CharField(max_length=75)),
                (
                    "subtag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.grandfatheredlang",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("subtag", "index")},
            },
        ),
    ]
