# Generated by Django 4.1.1 on 2022-10-22 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lang",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "part_3",
                    models.CharField(
                        max_length=3,
                        unique=True,
                        verbose_name="alpha-3 code (ISO 639-3)",
                    ),
                ),
                (
                    "part_1",
                    models.CharField(
                        max_length=2, null=True, verbose_name="alpha-2 code (ISO 639-1)"
                    ),
                ),
                (
                    "part_2b",
                    models.CharField(
                        max_length=3,
                        null=True,
                        verbose_name="bibliographic code (ISO 639-2/B)",
                    ),
                ),
                (
                    "part_2t",
                    models.CharField(
                        max_length=3,
                        null=True,
                        verbose_name="terminological code (ISO 639-2/T)",
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("I", "individual"),
                            ("M", "macrolanguage"),
                            ("S", "special"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "lang_type",
                    models.CharField(
                        choices=[
                            ("A", "ancient"),
                            ("C", "constructed"),
                            ("E", "extinct"),
                            ("H", "historical"),
                            ("L", "living"),
                            ("S", "special"),
                        ],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                ("ref_name", models.CharField(max_length=150)),
                ("comment", models.CharField(max_length=150, null=True)),
                (
                    "is_wordnet_supported",
                    models.BooleanField(
                        default=False,
                        verbose_name="supported by the Open Multilingual Wordnet",
                    ),
                ),
                (
                    "macrolang",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="individuals",
                        to="language.lang",
                        verbose_name="macrolanguage",
                    ),
                ),
            ],
            options={
                "verbose_name": "language",
            },
        ),
        migrations.CreateModel(
            name="LangTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tag", models.CharField(max_length=3)),
                (
                    "tag_type",
                    models.CharField(
                        choices=[
                            ("L", "language"),
                            ("E", "external language"),
                            ("R", "region"),
                            ("S", "script"),
                            ("V", "variant"),
                            ("G", "grandfathered"),
                            ("X", "redundant"),
                            ("P", "private use"),
                        ],
                        max_length=1,
                        verbose_name="type",
                    ),
                ),
                (
                    "deprecated",
                    models.DateField(null=True, verbose_name="date deprecated"),
                ),
                ("added", models.DateField(verbose_name="date added")),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("C", "collection"),
                            ("M", "macrolanguage"),
                            ("S", "special"),
                        ],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("macrolang", models.CharField(max_length=4, null=True)),
                ("comment", models.CharField(max_length=150, null=True)),
                ("subtag", models.CharField(max_length=12)),
                ("preferred_value", models.CharField(max_length=12, null=True)),
                ("suppress_script", models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PosTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbr", models.CharField(max_length=5, verbose_name="abbreviation")),
                ("name", models.CharField(max_length=126)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("O", "open class"),
                            ("C", "closed class"),
                            ("X", "other"),
                        ],
                        max_length=1,
                    ),
                ),
            ],
            options={
                "verbose_name": "universal POS tag",
            },
        ),
        migrations.CreateModel(
            name="SpacyModelSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
                (
                    "scale",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="small-to-large scale"
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpacyModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LangName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "printable",
                    models.CharField(
                        max_length=75, verbose_name="printable translated name"
                    ),
                ),
                (
                    "inverted",
                    models.CharField(
                        max_length=75, verbose_name="inverted translated name"
                    ),
                ),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="names",
                        to="language.lang",
                    ),
                ),
            ],
            options={
                "verbose_name": "language name",
            },
        ),
        migrations.CreateModel(
            name="SpacyLangModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=12)),
                ("package_version", models.CharField(max_length=126)),
                ("downloaded", models.BooleanField(default=False)),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="language.lang"
                    ),
                ),
                (
                    "model_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.spacymodelsize",
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="language.spacymodeltype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("lang", "model_type", "genre", "model_size", "package_version")
                },
            },
        ),
        migrations.CreateModel(
            name="LangSubtagPrefix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("text", models.CharField(max_length=150)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prefixes",
                        to="language.langtag",
                    ),
                ),
            ],
            options={
                "unique_together": {("tag", "index"), ("tag", "text")},
            },
        ),
        migrations.CreateModel(
            name="LangSubtagDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveSmallIntegerField()),
                ("text", models.CharField(max_length=150)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="language.langtag",
                    ),
                ),
            ],
            options={
                "unique_together": {("tag", "index"), ("tag", "text")},
            },
        ),
    ]
