# Generated by Django 4.1.2 on 2022-10-24 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="subtagprefix",
            old_name="tag",
            new_name="subtag",
        ),
        migrations.AlterUniqueTogether(
            name="subtagprefix",
            unique_together={("subtag", "index"), ("subtag", "text")},
        ),
    ]
