# Generated by Django 4.1.1 on 2022-10-22 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0002_rename_langsubtagdescription_langtagdescription_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="langtagdescription",
            options={"verbose_name": "RFC5646 language tag description"},
        ),
        migrations.AlterModelOptions(
            name="langtagprefix",
            options={"verbose_name": "RFC5646 language tag prefix"},
        ),
    ]
