# Generated by Django 4.1.2 on 2022-10-25 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carpet", "0001_initial"),
        ("maas", "0001_initial"),
        ("language", "0002_rename_tag_subtagprefix_subtag_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Lang",
            new_name="IsoLang",
        ),
        migrations.RenameModel(
            old_name="LangName",
            new_name="IsoLangName",
        ),
        migrations.AlterModelOptions(
            name="subtag",
            options={"verbose_name": "BCP 47 language subtag"},
        ),
        migrations.RenameField(
            model_name="googlelang",
            old_name="lang",
            new_name="iso_lang",
        ),
        migrations.RenameField(
            model_name="isolangname",
            old_name="lang",
            new_name="iso_lang",
        ),
        migrations.RenameField(
            model_name="langtag",
            old_name="lang",
            new_name="iso_lang",
        ),
        migrations.RenameField(
            model_name="spacylangmodel",
            old_name="lang",
            new_name="iso_lang",
        ),
        migrations.AlterUniqueTogether(
            name="spacylangmodel",
            unique_together={
                ("iso_lang", "model_type", "genre", "model_size", "package_version")
            },
        ),
    ]
