# Generated by Django 4.1.1 on 2022-10-22 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0003_alter_langtagdescription_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LangSubtagRegistry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_date", models.DateField()),
                ("saved", models.DateTimeField()),
            ],
            options={
                "verbose_name": "IANA Language Subtag Registry",
            },
        ),
        migrations.RemoveField(
            model_name="langtag",
            name="preferred_value",
        ),
        migrations.RemoveField(
            model_name="langtag",
            name="tag",
        ),
        migrations.AddField(
            model_name="langtag",
            name="pref_value",
            field=models.CharField(
                max_length=12, null=True, verbose_name="preferred value"
            ),
        ),
        migrations.AlterField(
            model_name="langtag",
            name="macrolang",
            field=models.CharField(
                max_length=4, null=True, verbose_name="macrolanguage"
            ),
        ),
        migrations.AddField(
            model_name="langtag",
            name="registry",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtags",
                to="language.langsubtagregistry",
            ),
            preserve_default=False,
        ),
    ]
