# Generated by Django 4.1.1 on 2022-10-23 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("language", "0004_langsubtagregistry_remove_langtag_preferred_value_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="langtag",
            name="tag",
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name="langtag",
            name="scope",
            field=models.CharField(
                choices=[
                    ("C", "collection"),
                    ("M", "macrolanguage"),
                    ("S", "special"),
                    ("P", "private use"),
                ],
                max_length=1,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="langtag",
            name="subtag",
            field=models.CharField(max_length=12, null=True),
        ),
    ]
