ca_core_news_md: [Multilingual Central Repository]
zh_core_web_md: [Chinese Open Wordnet, Chinese Wordnet (Taiwan)]
hr_core_news_md: [Croatian Wordnet]
da_core_news_md: [DanNet]
en_core_web_md: [Princeton Wordnet, Open English Wordnet]
fi_core_news_md: [FinnWordNet]
fr_core_news_md: [WOLF (Wordnet Libre du Français)]
el_core_news_md: [Greek Wordnet]
it_core_news_md: [MultiWordNet, ItalWordnet]
ja_core_news_md: [Japanese Wordnet]
lt_core_news_md: [Lithuanian WordNet]
nb_core_news_md: [Norwegian Wordnet]
pl_core_news_md: [plWordNet]
ro_core_news_md: [Romanian Wordnet]
es_core_news_md: [Multilingual Central Repository]
sv_core_news_md: [Swedish (SALDO)]
