# Generated by Django 4.1.1 on 2022-10-03 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarpetPhrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("index", models.SmallIntegerField(default=0)),
                ("has_braces", models.BooleanField(default=False)),
                ("tone_changes", models.CharField(max_length=126)),
                ("suffixes", models.CharField(max_length=126)),
                ("multiplier", models.PositiveSmallIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CoreDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("term", models.CharField(max_length=254, unique=True)),
                (
                    "phrase",
                    models.TextField(null=True, verbose_name="definition in LilyPond"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Definition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(null=True)),
                ("term", models.CharField(max_length=254, unique=True)),
                ("source_file", models.CharField(max_length=254, null=True)),
                (
                    "carpet_phrase",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="moss.carpetphrase",
                    ),
                ),
                (
                    "core_synonym",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synonyms",
                        to="moss.coredefinition",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="carpetphrase",
            name="definition_child",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="moss.definition",
            ),
        ),
        migrations.AddField(
            model_name="carpetphrase",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="moss.carpetphrase",
            ),
        ),
    ]
