# Generated by Django 4.1.1 on 2022-10-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("moss", "0002_postag_definition_pos_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postag",
            options={"verbose_name": "Universal POS tag"},
        ),
        migrations.AlterField(
            model_name="definition",
            name="term",
            field=models.CharField(max_length=254),
        ),
        migrations.AddConstraint(
            model_name="definition",
            constraint=models.UniqueConstraint(
                models.F("term"),
                models.F("pos_tag"),
                models.F("notes"),
                name="unique_definition",
            ),
        ),
    ]
