# Generated by Django 4.1.1 on 2022-10-09 16:17

import carpet.common
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maas", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("has_braces", models.BooleanField(default=False)),
                (
                    "pitch_change",
                    models.CharField(
                        choices=[("+", "up"), ("-", "down"), ("@", "last")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("multiplier", models.PositiveSmallIntegerField(default=1)),
                ("count", models.PositiveSmallIntegerField(null=True)),
                (
                    "suffix",
                    models.CharField(
                        choices=[("?", "question"), ("!", "not")],
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "lexeme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="maas.lexeme",
                    ),
                ),
            ],
            bases=(models.Model, carpet.common.AbstractPhrase),
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english", models.CharField(max_length=254)),
                ("source_file", models.CharField(max_length=254, null=True)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defined_term",
                        to="carpet.phrase",
                    ),
                ),
                (
                    "pos_tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="maas.postag"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhraseComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.SmallIntegerField()),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_rels",
                        to="carpet.phrase",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_rels",
                        to="carpet.phrase",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                models.F("english"),
                models.F("pos_tag"),
                name="no_duplicate_definitions",
            ),
        ),
        migrations.AddConstraint(
            model_name="phrasecomposition",
            constraint=models.UniqueConstraint(
                models.F("parent"),
                models.F("index"),
                name="no_duplicate_subphrase_indices",
            ),
        ),
    ]
