# Generated by Django 4.1.2 on 2022-11-20 00:47

import carpet.base
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Phrase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pitch_change",
                    models.CharField(
                        choices=[("+", "up"), ("-", "down"), ("$", "last")],
                        max_length=1,
                        null=True,
                    ),
                ),
                ("multiplier", models.PositiveSmallIntegerField(default=1)),
                ("count", models.PositiveSmallIntegerField(null=True)),
                (
                    "suffix",
                    models.CharField(
                        choices=[("?", "what"), ("!", "not")], max_length=1, null=True
                    ),
                ),
            ],
            bases=(models.Model, carpet.base.AbstractPhrase),
        ),
        migrations.CreateModel(
            name="SynsetDef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pos",
                    models.CharField(
                        choices=[
                            ("a", "adjective"),
                            ("s", "satellite adjective"),
                            ("r", "adverb"),
                            ("n", "noun"),
                            ("v", "verb"),
                        ],
                        max_length=1,
                    ),
                ),
                ("wn_offset", models.PositiveBigIntegerField()),
                ("source_file", models.CharField(max_length=254, null=True)),
                (
                    "phrase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="defined_synsets",
                        to="carpet.phrase",
                    ),
                ),
            ],
            options={
                "verbose_name": "synset definition",
            },
        ),
        migrations.CreateModel(
            name="PhraseComposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.SmallIntegerField()),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_rels",
                        to="carpet.phrase",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_rels",
                        to="carpet.phrase",
                    ),
                ),
            ],
            options={
                "ordering": ("parent", "index"),
            },
        ),
    ]
