# Generated by Django 4.1.2 on 2022-11-23 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("carpet", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="synsetdef",
            name="pos",
            field=models.CharField(
                choices=[
                    ("a", "adjective"),
                    ("s", "satellite adjective"),
                    ("r", "adverb"),
                    ("n", "noun"),
                    ("v", "verb"),
                ],
                max_length=1,
                verbose_name="part of speech",
            ),
        ),
        migrations.AlterField(
            model_name="synsetdef",
            name="wn_offset",
            field=models.PositiveBigIntegerField(verbose_name="offset"),
        ),
    ]
