# Generated by Django 4.1.2 on 2022-12-02 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jangle", "0003_alter_ianasubtagdescription_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpacyModelSize",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
                (
                    "scale",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="small-to-large scale"
                    ),
                ),
                ("name", models.CharField(max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="SpacyModelType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="abbreviation"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoogleLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(max_length=254)),
                ("supports_source", models.BooleanField()),
                ("supports_target", models.BooleanField()),
                (
                    "lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jangle.languagetag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Google Cloud Translate API language",
            },
        ),
        migrations.CreateModel(
            name="SpacyLanguage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("genre", models.CharField(max_length=12)),
                ("package_version", models.CharField(max_length=126)),
                ("downloaded", models.BooleanField(default=False)),
                (
                    "iso_lang",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jangle.isolanguage",
                    ),
                ),
                (
                    "model_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="translator.spacymodelsize",
                    ),
                ),
                (
                    "model_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="translator.spacymodeltype",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("iso_lang", "model_type", "genre", "model_size", "package_version")
                },
            },
        ),
    ]
