# Generated by Django 4.1.2 on 2022-11-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="googlelanguage",
            name="display_name",
            field=models.CharField(max_length=254),
        ),
    ]
